services:
  postgres:
    image: postgres:16
    container_name: tripwise-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tripwise
    ports:
      - "5432:5432"
    volumes:
      - tripwise_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  tripwise_postgres_data:
    driver: local
